---
development:
  cloud_name: <%= ENV["FOODORA_CLOUD_NAME"] %>
  api_key: <%= ENV["FOODORA_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["FOODORA_CLOUDINARY_SECRET_KEY"] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: <%= ENV["FOODORA_CLOUD_NAME"] %>
  api_key: <%= ENV["FOODORA_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["FOODORA_CLOUDINARY_SECRET_KEY"] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: <%= ENV["FOODORA_CLOUD_NAME"] %>
  api_key: <%= ENV["FOODORA_CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["FOODORA_CLOUDINARY_SECRET_KEY"] %>
  enhance_image_tag: true
  static_image_support: false
