production:
  foodora_stripe_publishable_key: <%= ENV["FOODORA_STRIPE_PUBLISHABLE_KEY"] %>
  foodora_stripe_secret_key: <%= ENV["FOODORA_STRIPE_SECRET_KEY"] %>
  foodora_mailgun_domain_url: <%= ENV["FOODORA_MAILGUN_DOMAIN_URL"] %>
  foodora_mailgun_default_smtp: <%= ENV["FOODORA_MAILGUN_DEFAULT_SMTP"] %>
  foodora_mailgun_password: <%= ENV["FOODORA_MAILGUN_PASSWORD"] %>
  foodora_mailgun_api_key: <%= ENV["FOODORA_MAILGUN_API_KEY"] %>
  foodora_cloud_name: <%= ENV["FOODORA_CLOUD_NAME"] %>
  foodora_cloudinary_api_key: <%= ENV["FOODORA_CLOUDINARY_API_KEY"] %>
  foodora_cloudinary_secret_key: <%= ENV["FOODORA_CLOUDINARY_SECRET_KEY"] %>
